window.GAMES = [
  {
    id: 1,
    slug: "geometry-jump",
    title: "Geometry Jump",
    description: "Jump over obstacles in this fast-paced geometry-based platformer! Time your jumps perfectly to avoid spikes and reach the finish line.",
    category: "geometry-dash",
    thumb: "images/geometry-jump.png",
    iframeUrl: "https://1games.io/game/geometry-jump/",
    tags: ["platformer", "jumping", "geometry", "arcade", "skill"],
    instructions: ["Click or spacebar to jump", "Time your jumps carefully", "Avoid spikes and obstacles", "Reach the end to complete level"],
    rating: 4.8,
    dateAdded: "2025-06-10"
  },
  {
    id: 2,
    slug: "geometry-arrow",
    title: "Geometry Arrow",
    description: "Navigate through geometric mazes with precise arrow movements! Control your arrow through challenging levels filled with obstacles.",
    category: "geometry-dash",
    thumb: "images/geometry-arrow.png",
    iframeUrl: "https://1games.io/embed/geometry-arrow",
    tags: ["geometry", "arrow", "maze", "precision", "arcade","skill"],
    instructions: ["Arrow keys to move", "Navigate through obstacles", "Collect gems along the way", "Reach the target to advance"],
    rating: 4.6,
    dateAdded: "2025-06-08"
  },
  {
    id: 3,
    slug: "wave-dash",
    title: "WAVE Dash",
    description: "Jump and fly your way through danger in this rhythm-based action platformer! Navigate through impossible levels with perfect timing.",
    category: "geometry-dash",
    thumb: "images/wave-dash.jpg",
    iframeUrl: "https://www.jopi.com/embed.php?game=geometry-dash",
    tags: ["platformer", "rhythm", "challenging", "music", "geometry","skill"],
    instructions: ["Click or spacebar to jump", "Follow the music rhythm", "Avoid spikes and obstacles", "Practice mode available"],
    rating: 4.7,
    dateAdded: "2025-06-05"
  },
  {
    id: 4,
    slug: "geometry-dash-black-wave",
    title: "Geometry Dash Black Wave",
    description: "Master the wave gamemode in this intense Geometry Dash level! Navigate through tight spaces with fluid wave movements.",
    category: "geometry-dash",
    thumb: "images/geometry-dash-black-wave.jpg",
    iframeUrl: "https://g.vseigru.net/7/igra-chjornaya-geometri-volna-super-chellendzh/",
    tags: ["wave", "geometry-dash", "challenging", "dark", "precision","skill"],
    instructions: ["Hold to go up, release to go down", "Navigate through narrow passages", "Perfect timing is essential", "Avoid hitting walls"],
    rating: 4.9,
    dateAdded: "2025-06-01"
  },
  {
    id: 5,
    slug: "geometry-dash-black-wave-2",
    title: "Geometry Dash Black Wave 2",
    description: "The sequel to Black Wave with even more challenging wave sequences! Test your skills in this advanced geometry level.",
    category: "geometry-dash",
    thumb: "images/geometry-dash-black-wave2.jpg",
    iframeUrl: "https://yandex.com/games/app/307214?utm_source=distrib&amp;utm_medium=geometrydashwave.com",
    tags: ["wave", "sequel", "hard", "geometry-dash", "expert","skill"],
    instructions: ["Hold to ascend, release to descend", "Master wave physics", "Navigate tight corridors", "Patience and practice required"],
    rating: 4.5,
    dateAdded: "2025-05-28"
  },
  {
    id: 6,
    slug: "geometry-dash-black-wave-3",
    title: "Geometry Dash Black Wave 3",
    description: "The third installment of the Black Wave series with new mechanics and obstacles! Can you conquer this ultimate wave challenge?",
    category: "geometry-dash",
    thumb: "images/geometry-dash-black-wave3.jpg",
    iframeUrl: "https://g.vseigru.net/7/igra-chjornaya-geometri-volna-super-chellendzh/",
    tags: ["wave", "trilogy", "extreme", "geometry-dash", "mechanics","skill"],
    instructions: ["Control wave movement", "Learn new wave patterns", "Adapt to changing gravity", "Complete all checkpoints"],
    rating: 4.4,
    dateAdded: "2025-05-25"
  },
  {
    id: 7,
    slug: "geometry-dash-black-wave-4",
    title: "Geometry Dash Black Wave 4",
    description: "Push your wave skills to the limit in the fourth Black Wave adventure! Experience new level design and wave challenges.",
    category: "geometry-dash",
    thumb: "images/geometry-dash-black-wave4.jpg",
    iframeUrl: "https://yandex.com/games/app/344498?utm_source=distrib&amp;utm_medium=space-waves.co&amp;clid=10575041",
    tags: ["wave", "advanced", "black-series", "geometry-dash", "skill"],
    instructions: ["Master wave control", "Navigate complex patterns", "Use checkpoints wisely", "Focus on smooth movements"],
    rating: 4.3,
    dateAdded: "2025-05-20"
  },
  {
    id: 8,
    slug: "geometry-dash-black-wave-5",
    title: "Geometry Dash Black Wave 5",
    description: "The epic finale of the Black Wave series! Face the ultimate wave challenge with the most complex patterns yet.",
    category: "geometry-dash",
    thumb: "images/geometry-dash-black-wave5.jpg",
    iframeUrl: "https://app-373298.games.s3.yandex.net/373298/r8k1p219s59kjpid5ymnkvyfb59shfd2/index.html?sdk=%2Fsdk%2F_%2Fv2.5bc8bbec2107c9209400.js#origin=https%3A%2F%2Fallwebgames.com&amp;app-id=373298&amp;device-type=desktop",
    tags: ["wave", "finale", "ultimate", "geometry-dash", "mastery","skill"],
    instructions: ["Perfect wave technique required", "Handle multiple wave types", "Memorize difficult sections", "Never give up!"],
    rating: 4.6,
    dateAdded: "2025-05-15"
  },
  {
    id: 9,
    slug: "geometry-dash-wave",
    title: "Geometry Dash Wave",
    description: "Experience pure wave gameplay in this classic Geometry Dash mode! Master the art of wave navigation through various obstacles.",
    category: "geometry-dash",
    thumb: "images/Geometry Dash Wave.jpg",
    iframeUrl: "https://www.jopi.com/embed.php?game=geometry-dash-wave",
    tags: ["wave", "classic", "geometry-dash", "pure", "original","skill"],
    instructions: ["Hold to rise, release to fall", "Control wave amplitude", "Avoid ceiling and floor", "Maintain steady rhythm"],
    rating: 4.7,
    dateAdded: "2024-11-25"
  },
  {
    id: 10,
    slug: "geometry-dash-hyper-wave-neon-challenge",
    title: "Geometry Dash Hyper Wave Neon Challenge",
    description: "Enter a neon-lit hyper wave challenge with intense visuals and fast-paced gameplay! Can you handle the speed?",
    category: "geometry-dash",
    thumb: "images/Geometry Dash Hyper Wave Neon Challenge.jpg",
    iframeUrl: "https://www.jopi.com/embed.php?game=geometry-dash-hyper-wave-neon-challenge",
    tags: ["hyper", "neon", "fast", "wave", "visual","skill"],
    instructions: ["React quickly to changes", "Handle high-speed wave", "Follow neon indicators", "Stay focused on patterns"],
    rating: 4.2,
    dateAdded: "2024-09-15"
  },
  {
    id: 11,
    slug: "smash-karts-io",
    title: "Smash Karts IO",
    description: "Race against players worldwide in this action-packed kart racing battle royale! Collect weapons and smash your opponents!",
    category: "multiplayer",
    thumb: "images/Smash Karts IO.jpg",
    iframeUrl: "https://www.jopi.com/embed.php?game=smash-karts-io",
    tags: ["racing", "multiplayer", "battle-royale", "karts", "weapons"],
    instructions: ["WASD or arrow keys to drive", "Collect weapon boxes", "Attack other players", "Be the last kart standing"],
    rating: 4.8,
    dateAdded: "2025-06-13"
  },
  {
    id: 12,
    slug: "paper-io-2",
    title: "Paper IO 2",
    description: "Conquer territory by drawing lines and creating closed shapes! Avoid other players while expanding your paper empire.",
    category: "io",
    thumb: "images/Paper IO 2.jpg",
    iframeUrl: "https://www.jopi.com/embed.php?game=paper-io-2",
    tags: ["territory", "io-game", "strategy", "multiplayer", "conquest"],
    instructions: ["Move to draw lines", "Return to your territory to claim area", "Avoid hitting other players' lines", "Expand your territory"],
    rating: 4.1,
    dateAdded: "2024-08-20"
  },
  {
    id: 13,
    slug: "geometry-dash-breeze",
    title: "Geometry Dash Breeze",
    description: "Experience a refreshing breeze of challenges in this smooth Geometry Dash level! Navigate through flowing obstacles with graceful movements.",
    category: "geometry-dash",
    thumb: "images/geometry-dash-breeze.jpg",
    iframeUrl: "https://1games.io/game/geometry-dash-breeze/",
    tags: ["geometry-dash", "breeze", "smooth", "flowing", "relaxing","skill"],
    instructions: ["Click or spacebar to jump", "Follow the gentle rhythm", "Navigate through wind-like obstacles", "Enjoy the smooth gameplay"],
    rating: 4.6,
    dateAdded: "2025-6-14"
  },
  {
    id: 14,
    slug: "geometry-dash-world",
    title: "Geometry Dash World",
    description: "Explore different worlds in this expanded Geometry Dash adventure! Travel through various themed levels with unique challenges.",
    category: "geometry-dash",
    thumb: "images/geometry-dash-world.png",
    iframeUrl: "https://1games.io/game/geometry-dash-world/",
    tags: ["geometry-dash", "world", "adventure", "themed", "exploration","skill"],
    instructions: ["Jump with spacebar or click", "Explore different world themes", "Master various level mechanics", "Unlock new worlds by progressing"],
    rating: 4.6,
    dateAdded: "2025-6-14"
  },
  {
    id: 15,
    slug: "geometry-vibes",
    title: "Geometry Vibes",
    description: "Feel the rhythm and vibes in this energetic Geometry Dash experience! Sync your movements with the beat and overcome vibrant challenges.",
    category: "geometry-dash",
    thumb: "images/geometry-vibes.webp",
    iframeUrl: "https://1games.io/embed/geometry-vibes",
    tags: ["geometry-dash", "vibes", "rhythm", "energetic", "music","skill"],
    instructions: ["Jump with spacebar or click", "Feel the music rhythm", "Navigate colorful obstacles", "Stay in sync with the beat"],
    rating: 4.7,
    dateAdded: "2025-06-15"
  },
  {
    id: 16,
    slug: "space-waves",
    title: "Space Waves",
    description: "Journey through space with wave-based gameplay! Navigate your ship through cosmic obstacles in this stellar adventure.",
    category: "geometry-dash",
    thumb: "images/space-waves.webp",
    iframeUrl: "https://crazygames.com/embed/space-waves",
    tags: ["geometry-dash", "space", "waves", "cosmic", "adventure","skill"],
    instructions: ["Hold to ascend, release to descend", "Navigate through space debris", "Collect space gems", "Avoid asteroid obstacles"],
    rating: 4.5,
    dateAdded: "2025-06-15"
  },
  {
    id: 17,
    slug: "geometry-game-3d",
    title: "Geometry Game 3D",
    description: "Experience Geometry Dash in a whole new dimension! Navigate through 3D geometric landscapes with enhanced depth and perspective.",
    category: "geometry-dash",
    thumb: "images/geometry-game-3d.webp",
    iframeUrl: "https://1games.io/embed/geometry-game-3d",
    tags: ["geometry-dash", "3d", "dimension", "perspective", "geometric","skill"],
    instructions: ["Use spacebar to jump", "Navigate 3D obstacles", "Adjust to depth perception", "Master dimensional gameplay"],
    rating: 4.6,
    dateAdded: "2025-06-15"
  },
  {
    id: 18,
    slug: "wave-road",
    title: "Wave Road",
    description: "Travel down the endless wave road with precise control! Master the art of wave navigation on this challenging geometric highway.",
    category: "geometry-dash",
    thumb: "images/wave-road.webp",
    iframeUrl: "https://1games.io/embed/wave-road",
    tags: ["geometry-dash", "wave", "road", "highway", "precision"],
    instructions: ["Control wave movement", "Stay on the road path", "Avoid falling off edges", "Maintain steady rhythm"],
    rating: 4.4,
    dateAdded: "2025-06-15"
  },
  {
    id: 19,
    slug: "food-rush",
    title: "Food Rush",
    description: "Rush through delicious food combinations in this fast-paced match-3 adventure! Match tasty treats and complete cooking challenges.",
    category: "match3",
    thumb: "images/food-rush.jpg",
    iframeUrl: "https://play.famobi.com/food-rush/A-FAMOBI-COM",
    tags: ["match3", "food", "cooking", "fast-paced", "delicious"],
    instructions: ["Match 3 or more identical food items", "Complete cooking objectives", "Use power-ups to clear obstacles", "Beat level targets within moves"],
    rating: 4.6,
    dateAdded: "2025-06-16"
  },
  {
    id: 20,
    slug: "tile-journey",
    title: "Tile Journey",
    description: "Embark on an epic tile-matching journey across mystical lands! Solve challenging puzzles and unlock ancient secrets.",
    category: "match3",
    thumb: "images/tile-journey.jpg",
    iframeUrl: "https://play.famobi.com/tile-journey/A1000-10E",
    tags: ["match3", "journey", "adventure", "mystical", "tiles"],
    instructions: ["Match 3 or more tiles of the same type", "Clear paths to progress", "Collect special artifacts", "Solve each level's unique challenge"],
    rating: 4.5,
    dateAdded: "2025-06-16"
  },
  {
    id: 21,
    slug: "diamond-rush-2",
    title: "Diamond Rush 2",
    description: "The ultimate diamond hunting adventure returns! Match sparkling diamonds and precious gems in this thrilling sequel.",
    category: "match3",
    thumb: "images/diamond-rush-2.jpg",
    iframeUrl: "https://play.famobi.com/diamond-rush-2",
    tags: ["match3", "diamond", "gems", "treasure", "sequel"],
    instructions: ["Match 3+ diamonds to collect them", "Create special gem combinations", "Complete mining objectives", "Discover rare diamond formations"],
    rating: 4.7,
    dateAdded: "2025-06-16"
  },
  {
    id: 22,
    slug: "garden-bloom",
    title: "Garden Bloom",
    description: "Create beautiful flower gardens by matching colorful blooms! Help flowers grow and bloom in this peaceful gardening puzzle.",
    category: "match3",
    thumb: "images/garden-bloom.jpg",
    iframeUrl: "https://gardenbloom.h5games.usercontent.goog/v/03uof2ceev9h8/?origin=https%3A%2F%2Framesnacks.com&amp.gameCenter1d=ramesnacks&amp",
    tags: ["match3", "garden", "flowers", "nature", "peaceful"],
    instructions: ["Match flower buds to make them bloom", "Create garden patterns", "Use garden tools for special effects", "Complete seasonal challenges"],
    rating: 4.4,
    dateAdded: "2025-06-16"
  },
  {
    id: 23,
    slug: "garden-match-3d",
    title: "Garden Match 3D",
    description: "Experience match-3 in stunning 3D! Design and maintain beautiful gardens while solving engaging three-dimensional puzzles.",
    category: "match3",
    thumb: "images/garden-match-3d.jpg",
    iframeUrl: "https://play.famobi.com/garden-match-3d",
    tags: ["match3", "3d", "garden", "design", "beautiful"],
    instructions: ["Match items in 3D space", "Rotate view to find matches", "Decorate your garden", "Complete landscaping projects"],
    rating: 4.6,
    dateAdded: "2025-06-16"
  },
  {
    id: 24,
    slug: "zoo-boom",
    title: "Zoo Boom",
    description: "Join the wildest zoo adventure! Match animal tiles and help zoo animals in this explosive and fun-filled puzzle game.",
    category: "match3",
    thumb: "images/zoo-boom.jpg",
    iframeUrl: "https://play.famobi.com/zoo-boom",
    tags: ["match3", "zoo", "animals", "explosive", "adventure"],
    instructions: ["Match 3 or more animal tiles", "Rescue zoo animals", "Create powerful animal combos", "Complete zoo missions"],
    rating: 4.5,
    dateAdded: "2025-06-16"
  },
  {
    id: 25,
    slug: "bubble-woods",
    title: "Bubble Woods",
    description: "Pop your way through enchanted forest bubbles! Aim, match colors, and clear the magical woodland in this bubble shooter adventure.",
    category: "match3",
    thumb: "images/bubble-woods.jpg",
    iframeUrl: "https://play.famobi.com/bubble-woods",
    tags: ["match3", "bubble", "forest", "magical", "shooter"],
    instructions: ["Aim and shoot colored bubbles", "Match 3+ bubbles of same color", "Clear forest paths", "Use special bubble power-ups"],
    rating: 4.7,
    dateAdded: "2025-06-16"
  },
  {
    id: 26,
    slug: "totemia-cursed-marbles",
    title: "Totemia: Cursed Marbles",
    description: "Break the ancient curse by matching mystical marbles! Shoot colored marbles to create matches and solve totemic puzzles.",
    category: "match3",
    thumb: "images/totemia-cursed-marbles.jpg",
    iframeUrl: "https://play.famobi.com/totemia-cursed-marbles",
    tags: ["match3", "marbles", "ancient", "mystical", "curse"],
    instructions: ["Shoot marbles to create matches", "Match 3+ marbles of same color", "Break the marble chains", "Complete totemic challenges"],
    rating: 4.8,
    dateAdded: "2025-06-16"
  },
  {
    id: 27,
    slug: "climbing-block",
    title: "Climbing Block",
    description: "Test your climbing skills in this challenging block adventure! Navigate through obstacles and reach new heights in this exciting vertical platformer.",
    category: "casual",
    thumb: "images/climbing-block.webp",
    iframeUrl: "https://www.crazygames.com/embed/climbing-block---let-s-up-llam",
    tags: ["casual", "climbing", "adventure", "skill", "platformer"],
    instructions: ["Use arrow keys or WASD to move", "Jump to climb higher blocks", "Avoid falling obstacles", "Reach the top to win"],
    rating: 4.8,
    dateAdded: "2025-06-17"
  },
  {
    id: 28,
    slug: "lumber-harvest-tree-cutting-game",
    title: "Lumber Harvest: Tree Cutting Game",
    description: "Experience the satisfying world of tree cutting and lumber harvesting! Manage your resources, upgrade your tools, and build a thriving lumber business.",
    category: "casual",
    thumb: "images/lumber-harvest.jpg",
    iframeUrl: "https://www.crazygames.com/embed/lumber-harvest-tree-cutting-game",
    tags: ["casual", "simulation", "management", "harvesting", "business"],
    instructions: ["Click to cut trees", "Collect lumber and resources", "Upgrade your equipment", "Expand your lumber empire"],
    rating: 4.7,
    dateAdded: "2025-06-17"
  },
  {
    id: 29,
    slug: "craft-market",
    title: "Craft Market",
    description: "Run your own craft market and create amazing items! Buy materials, craft products, and sell them to customers in this engaging business simulation.",
    category: "casual",
    thumb: "images/cubic-shop.avif",
    iframeUrl: "https://www.crazygames.com/embed/cubic-shop",
    tags: ["casual", "crafting", "business", "management", "market"],
    instructions: ["Buy raw materials", "Craft items in your workshop", "Set prices and sell products", "Upgrade your shop and equipment"],
    rating: 4.9,
    dateAdded: "2025-06-17"
  },
  {
    id: 30,
    slug: "stone-grass-mowing-simulator",
    title: "Stone Grass: Mowing Simulator",
    description: "Relax and enjoy the peaceful art of lawn mowing! Cut grass, maintain beautiful lawns, and experience the satisfaction of perfectly manicured landscapes.",
    category: "casual",
    thumb: "images/stone-grass.jpg",
    iframeUrl: "https://www.crazygames.com/embed/stone-grass-mowing-simulator",
    tags: ["casual", "simulation", "relaxing", "mowing", "peaceful"],
    instructions: ["Control the lawn mower", "Cut all the grass evenly", "Avoid obstacles and trees", "Complete each level perfectly"],
    rating: 4.8,
    dateAdded: "2025-06-17"
  },
  {
    id: 31,
    slug: "ragdoll-archers",
    title: "Ragdoll Archers",
    description: "Become a master archer in this fun physics-based shooting game! Aim carefully and watch as ragdoll enemies react to your precise arrows with hilarious physics.",
    category: "casual",
    thumb: "images/ragdoll-archers-cover.avif",
    iframeUrl: "https://www.crazygames.com/embed/ragdoll-archers",
    tags: ["casual", "archery", "physics", "ragdoll", "shooting"],
    instructions: ["Aim with mouse", "Click and drag to set power", "Release to shoot arrows", "Hit targets for maximum points"],
    rating: 4.6,
    dateAdded: "2025-06-17"
  },
  {
    id: 32,
    slug: "find-brainrot",
    title: "Find Brainrot",
    description: "Hunt for hidden brainrot content in this quirky search game! Use your detective skills to find all the hidden memes and internet culture references.",
    category: "casual",
    thumb: "images/find-brainrot.avif",
    iframeUrl: "https://www.crazygames.com/embed/find-brainrot",
    tags: ["casual", "hidden-object", "memes", "search", "internet-culture"],
    instructions: ["Click on hidden objects", "Find all brainrot references", "Use hints if you get stuck", "Complete each level quickly for bonus points"],
    rating: 4.3,
    dateAdded: "2025-06-22"
  },
  {
    id: 33,
    slug: "fragen",
    title: "Fragen",
    description: "Test your knowledge and quick thinking in this fast-paced question and answer game! Challenge yourself with diverse topics and improve your general knowledge.",
    category: "action",
    thumb: "images/fragen.avif",
    iframeUrl: "https://www.crazygames.com/embed/fragen",
    tags: ["action", "quiz", "knowledge", "questions", "trivia"],
    instructions: ["Read questions carefully", "Select the correct answer quickly", "Build up your score streak", "Challenge yourself with harder levels"],
    rating: 4.5,
    dateAdded: "2025-06-22"
  },
  {
    id: 34,
    slug: "toonle",
    title: "Toonle",
    description: "Enter the colorful world of Toonle! Create amazing cartoon adventures, design characters, and explore vibrant animated landscapes in this creative casual game.",
    category: "casual",
    thumb: "images/toonle.avif",
    iframeUrl: "https://www.crazygames.com/embed/toonle",
    tags: ["casual", "cartoon", "creative", "animation", "adventure"],
    instructions: ["Design your cartoon character", "Explore colorful worlds", "Create animated stories", "Complete creative challenges"],
    rating: 4.5,
    dateAdded: "2025-06-22"
  },
  {
    id: 35,
    slug: "construction-set-3d-builder",
    title: "Construction Set - 3D Builder",
    description: "Build amazing 3D structures with unlimited creativity! Use various construction tools and materials to create your dream buildings and landscapes.",
    category: "casual",
    thumb: "images/construction-set---3d-builder.avif",
    iframeUrl: "https://www.crazygames.com/embed/construction-set---3d-builder",
    tags: ["casual", "building", "3d", "construction", "creative"],
    instructions: ["Select building materials", "Place blocks in 3D space", "Rotate and position objects", "Save and share your creations"],
    rating: 4.7,
    dateAdded: "2025-06-22"
  },
  {
    id: 36,
    slug: "evo-fish",
    title: "Evo Fish",
    description: "Guide your fish through evolution in this underwater adventure! Eat smaller fish, avoid predators, and evolve into the ultimate sea creature.",
    category: "casual",
    thumb: "images/evo-fish.avif",
    iframeUrl: "https://www.crazygames.com/embed/evo-fish",
    tags: ["casual", "evolution", "fish", "underwater", "survival"],
    instructions: ["Eat smaller fish to grow", "Avoid larger predators", "Collect evolution points", "Unlock new fish species"],
    rating: 4.6,
    dateAdded: "2025-06-22"
  },
  {
    id: 37,
    slug: "street-food-simulator",
    title: "Street Food Simulator",
    description: "Run your own street food business! Cook delicious meals, serve hungry customers, and build the most popular food truck in the city.",
    category: "casual",
    thumb: "images/street-food-simulator.avif",
    iframeUrl: "https://www.crazygames.com/embed/street-food-simulator",
    tags: ["casual", "cooking", "business", "simulation", "food"],
    instructions: ["Take customer orders", "Cook food ingredients", "Serve meals quickly", "Upgrade your equipment and menu"],
    rating: 4.8,
    dateAdded: "2025-06-22"
  },
  {
    id: 38,
    slug: "capybara-clicker",
    title: "Capybara Clicker",
    description: "Click your way to capybara paradise! Collect adorable capybaras, unlock new varieties, and build the ultimate capybara collection.",
    category: "casual",
    thumb: "images/capybara-clicker.webp",
    iframeUrl: "https://www.crazygames.com/embed/capybara-clicker",
    tags: ["casual", "clicker", "capybara", "idle", "collection"],
    instructions: ["Click to collect capybaras", "Upgrade your clicking power", "Unlock new capybara types", "Build automatic capybara generators"],
    rating: 4.5,
    dateAdded: "2025-06-22"
  },
  {
    id: 39,
    slug: "brainrot-idle-clicker",
    title: "Brainrot Idle Clicker",
    description: "Embrace the chaos of internet culture in this addictive idle clicker! Generate memes, collect brainrot content, and watch your influence grow.",
    category: "casual",
    thumb: "images/brainrot-idle-clicker.avif",
    iframeUrl: "https://www.crazygames.com/embed/brainrot-idle-clicker",
    tags: ["casual", "idle", "clicker", "memes", "internet"],
    instructions: ["Click to generate brainrot", "Purchase upgrade generators", "Unlock new meme categories", "Maximize your viral potential"],
    rating: 4.4,
    dateAdded: "2025-06-22"
  },
  {
    id: 40,
    slug: "papaya-summer-farm",
    title: "Papaya Summer Farm",
    description: "Experience the joy of tropical farming! Grow exotic papayas, manage your summer farm, and create a thriving agricultural paradise.",
    category: "casual",
    thumb: "images/papaya-summer-farm.avif",
    iframeUrl: "https://www.crazygames.com/embed/papaya-summer-farm-sho",
    tags: ["casual", "farming", "tropical", "simulation", "agriculture"],
    instructions: ["Plant papaya seeds", "Water and care for crops", "Harvest ripe fruits", "Expand your farm operations"],
    rating: 4.6,
    dateAdded: "2025-06-22"
  },
  {
    id: 41,
    slug: "animal-dna-run",
    title: "Animal DNA Run",
    description: "Explore the mysteries of genetics! Control genetically modified animals in this sci-fi running game, traverse futuristic laboratories, collect DNA fragments, and unlock new genetic abilities.",
    category: "casual",
    thumb: "images/animal-dna-run.avif",
    iframeUrl: "https://www.crazygames.com/embed/animal-dna-run",
    tags: ["casual", "running", "dna", "science", "animals", "futuristic"],
    instructions: ["Control genetically modified animals", "Collect DNA fragments and energy", "Avoid laboratory obstacles", "Unlock new genetic abilities", "Explore scientific laboratories"],
    rating: 4.6,
    dateAdded: "2025-06-22"
  },
  {
    id: 42,
    slug: "layers-roll",
    title: "Layers Roll",
    description: "Roll through colorful layers in this satisfying puzzle game! Peel away layers, solve geometric puzzles, and reveal hidden patterns.",
    category: "casual",
    thumb: "images/layers-roll.avif",
    iframeUrl: "https://www.crazygames.com/embed/layers-roll",
    tags: ["casual", "puzzle", "layers", "rolling", "satisfying"],
    instructions: ["Swipe to roll layers", "Peel away outer layers", "Reveal the core pattern", "Complete each level efficiently"],
    rating: 4.5,
    dateAdded: "2025-06-22"
  },
  {
    id: 43,
    slug: "i-dont-even-know",
    title: "I Don't Even Know",
    description: "Embrace the absurd in this unpredictable game! Navigate through random challenges, bizarre scenarios, and unexpected gameplay mechanics.",
    category: "casual",
    thumb: "images/idk.avif",
    iframeUrl: "https://www.crazygames.com/embed/i-dont-even-know",
    tags: ["casual", "random", "absurd", "unpredictable", "humor"],
    instructions: ["Expect the unexpected", "Adapt to changing rules", "Embrace the chaos", "Just go with the flow"],
    rating: 4.3,
    dateAdded: "2025-06-22"
  },
  {
    id: 44,
    slug: "shovel-3d",
    title: "Shovel 3D",
    description: "Dig your way to treasure in this 3D excavation adventure! Use your shovel to uncover hidden artifacts, gems, and ancient treasures.",
    category: "casual",
    thumb: "images/shovel-3d.avif",
    iframeUrl: "https://www.crazygames.com/embed/shovel-3d",
    tags: ["casual", "digging", "3d", "treasure", "excavation"],
    instructions: ["Click and drag to dig", "Uncover buried treasures", "Avoid obstacles underground", "Complete excavation objectives"],
    rating: 4.4,
    dateAdded: "2025-06-22"
  },
  {
    id: 45,
    slug: "lazy-jumper",
    title: "Lazy Jumper",
    description: "Jump with style in this relaxed platformer! Control a lazy character through chill levels, collect items, and enjoy the laid-back gameplay.",
    category: "casual",
    thumb: "images/lazy-jumper.avif",
    iframeUrl: "https://www.crazygames.com/embed/lazy-jumper",
    tags: ["casual", "jumping", "relaxed", "platformer", "chill"],
    instructions: ["Tap to jump lazily", "Collect floating items", "Land on safe platforms", "Take your time and enjoy"],
    rating: 4.2,
    dateAdded: "2025-06-22"
  },
  {
    id: 46,
    slug: "mafia-business-empire-stickman-escape-3d",
    title: "Mafia Business Empire: Stickman Escape 3d",
    description: "Build your criminal empire and escape dangerous situations! Control stickman characters in this thrilling 3D mafia adventure game.",
    category: "casual",
    thumb: "images/mafia-business-empire-stickman-escap.avif",
    iframeUrl: "https://www.crazygames.com/embed/mafia-business-empire-stickman-escape-3d",
    tags: ["casual", "mafia", "stickman", "3d", "escape"],
    instructions: ["Build your criminal network", "Plan strategic escapes", "Avoid law enforcement", "Expand your mafia empire"],
    rating: 4.6,
    dateAdded: "2025-06-22"
  },
  {
    id: 47,
    slug: "fragen",
    title: "Fragen",
    description: "Test your knowledge and quick thinking in this fast-paced question and answer game! Challenge yourself with diverse topics and improve your general knowledge.",
    category: "action",
    thumb: "images/fragen.avif",
    iframeUrl: "https://www.crazygames.com/embed/fragen",
    tags: ["action", "quiz", "knowledge", "questions", "trivia"],
    instructions: ["Read questions carefully", "Select the correct answer quickly", "Build up your score streak", "Challenge yourself with harder levels"],
    rating: 4.5,
    dateAdded: "2025-06-22"
  },
  {
    id: 48,
    slug: "eternal-siege",
    title: "Eternal Siege",
    description: "Defend your fortress in this epic siege warfare game! Command armies, build defenses, and survive endless waves of attackers.",
    category: "action",
    thumb: "images/eternal-siege.avif",
    iframeUrl: "https://www.crazygames.com/embed/eternal-siege",
    tags: ["action", "strategy", "defense", "warfare", "siege"],
    instructions: ["Build defensive structures", "Command your troops", "Upgrade weapons and armor", "Survive the eternal siege"],
    rating: 4.7,
    dateAdded: "2025-06-22"
  },
  {
    id: 49,
    slug: "cowz-io",
    title: "Cowz.io",
    description: "Join the bovine battle royale! Control your cow warrior in this multiplayer arena and become the ultimate moo-master!",
    category: "action",
    thumb: "images/cowz-io.avif",
    iframeUrl: "https://www.crazygames.com/embed/cowz-io",
    tags: ["action", "multiplayer", "io-game", "battle-royale", "cows"],
    instructions: ["Move with WASD or arrow keys", "Left click to attack", "Collect power-ups", "Eliminate other players"],
    rating: 4.4,
    dateAdded: "2025-06-22"
  },
  {
    id: 50,
    slug: "archer-clash",
    title: "Archer Clash",
    description: "Master the art of archery in epic battles! Aim precisely, time your shots perfectly, and defeat enemy archers in intense duels.",
    category: "action",
    thumb: "images/archer-clash.avif",
    iframeUrl: "https://www.crazygames.com/embed/archer-clash-ftj",
    tags: ["action", "archery", "duels", "precision", "medieval"],
    instructions: ["Aim with mouse", "Hold and drag to set power", "Release to shoot arrows", "Hit enemies to win battles"],
    rating: 4.6,
    dateAdded: "2025-06-22"
  },
  {
    id: 51,
    slug: "war-v-survivor",
    title: "War V: Survivor",
    description: "Survive the ultimate war zone! Fight through hostile territories, upgrade your weapons, and become the last survivor standing.",
    category: "action",
    thumb: "images/war-v-survivor.avif",
    iframeUrl: "https://www.crazygames.com/embed/war-v-survivor",
    tags: ["action", "survival", "war", "shooting", "upgrade"],
    instructions: ["Move with WASD keys", "Aim and shoot with mouse", "Collect weapons and ammo", "Survive as long as possible"],
    rating: 4.8,
    dateAdded: "2025-06-22"
  },
  {
    id: 52,
    slug: "uncle-hit-punch-the-dummy",
    title: "Uncle Hit: Punch the Dummy",
    description: "Release your stress by punching the training dummy! Use various fighting techniques and combos to achieve the highest damage scores.",
    category: "action",
    thumb: "images/uncle-hit-punch-the-dummy.avif",
    iframeUrl: "https://www.crazygames.com/embed/uncle-hit-punch-the-dummy",
    tags: ["action", "fighting", "stress-relief", "training", "combos"],
    instructions: ["Click to punch the dummy", "Try different punch combinations", "Build up combo multipliers", "Achieve high damage scores"],
    rating: 4.3,
    dateAdded: "2025-06-22"
  },
  {
    id: 53,
    slug: "asteroid-breaker",
    title: "Asteroid Breaker",
    description: "Protect Earth from incoming asteroids! Pilot your spaceship through dangerous asteroid fields and blast them to pieces.",
    category: "action",
    thumb: "images/asteroid-breaker.avif",
    iframeUrl: "https://www.crazygames.com/embed/asteroid-breaker-ezu",
    tags: ["action", "space", "shooting", "asteroids", "defense"],
    instructions: ["Move spaceship with arrow keys", "Spacebar to shoot", "Destroy all asteroids", "Avoid collision with debris"],
    rating: 4.5,
    dateAdded: "2025-06-22"
  },
  {
    id: 54,
    slug: "crazy-vikings-life",
    title: "Crazy Vikings Life",
    description: "Experience the wild life of a Viking warrior! Raid villages, battle monsters, and build your legendary Viking saga.",
    category: "action",
    thumb: "images/crazy-vikings-life.avif",
    iframeUrl: "https://www.crazygames.com/embed/crazy-vikings-life",
    tags: ["action", "vikings", "adventure", "medieval", "warrior"],
    instructions: ["Control your Viking with WASD", "Attack with left click", "Collect loot and resources", "Complete Viking quests"],
    rating: 4.6,
    dateAdded: "2025-06-22"
  },
  {
    id: 55,
    slug: "crazy-miners",
    title: "Crazy Miners",
    description: "Join the underground mining mayhem! Compete with other miners, collect precious gems, and become the richest miner in the depths.",
    category: "action",
    thumb: "images/crazy-miners.avif",
    iframeUrl: "https://www.crazygames.com/embed/crazy-miners-multiplayer",
    tags: ["action", "mining", "multiplayer", "competition", "gems"],
    instructions: ["Move with WASD keys", "Mine blocks with left click", "Collect gems and resources", "Compete with other players"],
    rating: 4.4,
    dateAdded: "2025-06-22"
  },
  {
    id: 56,
    slug: "hero-3-flying-robot",
    title: "Hero 3: Flying Robot",
    description: "Soar through the skies as a powerful flying robot hero! Battle enemies in aerial combat and save the world from destruction.",
    category: "action",
    thumb: "images/hero-3-flying-robot.avif",
    iframeUrl: "https://www.crazygames.com/embed/hero-3-flying-robot",
    tags: ["action", "robot", "flying", "hero", "combat"],
    instructions: ["Fly with WASD or arrow keys", "Shoot with spacebar or click", "Use special abilities", "Complete heroic missions"],
    rating: 4.7,
    dateAdded: "2025-06-22"
  },
  {
    id: 57,
    slug: "street-fighter-simulator",
    title: "Street Fighter Simulator",
    description: "Master the art of street fighting! Learn powerful combos, special moves, and become the ultimate street fighting champion.",
    category: "action",
    thumb: "images/street-fighter-simulator.avif",
    iframeUrl: "https://www.crazygames.com/embed/street-fighter-simulator",
    tags: ["action", "fighting", "martial-arts", "combos", "tournament"],
    instructions: ["Use arrow keys to move", "A/S/D keys for different attacks", "Learn combo sequences", "Defeat all opponents"],
    rating: 4.8,
    dateAdded: "2025-06-22"
  },
  {
    id: 58,
    slug: "the-unfair-platformer",
    title: "The Unfair Platformer",
    description: "Face the most challenging and unfair platformer ever created! Navigate through devious traps, hidden spikes, and impossible jumps.",
    category: "action",
    thumb: "images/the-unfair-platformer.avif",
    iframeUrl: "https://www.crazygames.com/embed/the-unfair-platformer",
    tags: ["action", "platformer", "challenging", "difficult", "traps"],
    instructions: ["Arrow keys or WASD to move", "Spacebar to jump", "Expect the unexpected", "Don't give up, keep trying!"],
    rating: 4.2,
    dateAdded: "2025-06-22"
  },
  {
    id: 59,
    slug: "tap-reveal",
    title: "Tap Reveal",
    description: "Uncover hidden secrets with strategic tapping! Use logic and deduction to reveal patterns, solve mysteries, and unlock new levels in this engaging puzzle game.",
    category: "strategy",
    thumb: "images/tap-reveal.avif",
    iframeUrl: "https://www.crazygames.com/embed/tap-reveal",
    tags: ["strategy", "puzzle", "logic", "deduction", "mystery"],
    instructions: ["Tap on tiles to reveal content", "Use logical thinking to find patterns", "Deduce the correct sequence", "Complete objectives to advance"],
    rating: 4.4,
    dateAdded: "2025-06-22"
  },
  {
    id: 60,
    slug: "cups-water-sort-puzzle",
    title: "Cups - Water Sort Puzzle",
    description: "Sort colored water into matching cups in this relaxing strategy puzzle! Plan your moves carefully to organize all the water by color in the fewest steps possible.",
    category: "strategy",
    thumb: "images/cups---water-sort-puzzle.avif",
    iframeUrl: "https://www.crazygames.com/embed/cups---water-sort-puzzle",
    tags: ["strategy", "puzzle", "sorting", "logic", "relaxing"],
    instructions: ["Tap a cup to select it", "Tap another cup to pour water", "Sort water by matching colors", "Complete each level with minimum moves"],
    rating: 4.6,
    dateAdded: "2025-06-22"
  },
  {
    id: 61,
    slug: "the-dumb-test",
    title: "The Dumb Test",
    description: "Think you're smart? Take on this deceptively challenging intelligence test! Solve tricky questions, avoid obvious traps, and prove your mental agility.",
    category: "strategy",
    thumb: "images/the-dumb-test.avif",
    iframeUrl: "https://www.crazygames.com/embed/the-dumb-test",
    tags: ["strategy", "intelligence", "quiz", "tricky", "brain-teaser"],
    instructions: ["Read each question carefully", "Think outside the box", "Avoid obvious wrong answers", "Use logic and creativity to solve"],
    rating: 4.3,
    dateAdded: "2025-06-22"
  },
  {
    id: 62,
    slug: "golf-mania",
    title: "Golf Mania",
    description: "Experience the ultimate golf adventure! Master your swing, navigate challenging courses, and become a golf champion in this exciting sports simulation.",
    category: "sports",
    thumb: "images/golf-mania.avif",
    iframeUrl: "https://www.crazygames.com/embed/golf-mania",
    tags: ["sports", "golf", "simulation", "championship", "precision"],
    instructions: ["Aim your shot with mouse", "Click and drag to set power", "Release to swing the club", "Get the ball in the hole with fewest strokes"],
    rating: 4.5,
    dateAdded: "2025-06-22"
  },
  {
    id: 63,
    slug: "stunt-paradise",
    title: "Stunt Paradise",
    description: "Perform death-defying stunts in this extreme sports paradise! Jump, flip, and soar through incredible obstacle courses and become a stunt legend.",
    category: "sports",
    thumb: "images/stunt-paradise.avif",
    iframeUrl: "https://www.crazygames.com/embed/stunt-paradise",
    tags: ["sports", "stunts", "extreme", "acrobatics", "adventure"],
    instructions: ["Use arrow keys to control movement", "Spacebar for special stunts", "Land safely to score points", "Complete all stunt challenges"],
    rating: 4.7,
    dateAdded: "2025-06-22"
  },
  {
    id: 64,
    slug: "color-zone",
    title: "Color Zone",
    description: "Enter the colorful world of competitive sports! Match colors, complete challenges, and dominate the zone in this unique sports puzzle hybrid.",
    category: "sports",
    thumb: "images/color-zone.avif",
    iframeUrl: "https://www.crazygames.com/embed/color-zone",
    tags: ["sports", "color", "competition", "puzzle", "zone"],
    instructions: ["Match the required colors", "Complete zone objectives", "Beat time challenges", "Unlock new color zones"],
    rating: 4.4,
    dateAdded: "2025-06-22"
  },
  {
    id: 65,
    slug: "stickman-tennis-3d",
    title: "Stickman Tennis 3D",
    description: "Play tennis like never before in 3D! Control your stickman player, master powerful serves and volleys, and compete in thrilling tennis matches.",
    category: "sports",
    thumb: "images/stickman-tennis-3d.avif",
    iframeUrl: "https://www.crazygames.com/embed/stickman-tennis-3d",
    tags: ["sports", "tennis", "3d", "stickman", "competition"],
    instructions: ["Move with WASD or arrow keys", "Click to hit the ball", "Aim for opponent's weak spots", "Win sets to advance in tournament"],
    rating: 4.6,
    dateAdded: "2025-06-22"
  },
  {
    id: 66,
    slug: "afk-dungeon-idle-action-rpg",
    title: "AFK Dungeon: Idle Action RPG",
    description: "Explore mysterious dungeons and grow stronger in this idle action RPG! Auto-battle system lets your hero adventure continuously, collect equipment, upgrade skills, and become the ultimate dungeon conqueror.",
    category: "adventure",
    thumb: "images/afk-dungeon-zaq.webp",
    iframeUrl: "https://www.crazygames.com/embed/afk-dungeon-zaq",
    tags: ["adventure", "rpg", "idle", "dungeon", "action", "upgrade"],
    instructions: ["Choose your hero class", "Auto-explore dungeon levels", "Collect equipment and gold", "Upgrade skills and attributes", "Challenge deeper dungeon floors"],
    rating: 4.6,
    dateAdded: "2025-06-22"
  },
  {
    id: 67,
    slug: "metro-escape",
    title: "Metro Escape",
    description: "Survive in this intense metro escape game! Navigate through dangerous underground tunnels, solve puzzles, avoid traps, and find your way to freedom.",
    category: "adventure",
    thumb: "images/metro-escape.avif",
    iframeUrl: "https://www.crazygames.com/embed/metro-escape",
    tags: ["adventure", "escape", "puzzle", "survival", "underground", "thriller"],
    instructions: ["Explore metro stations and tunnels", "Collect useful items", "Solve complex puzzles", "Avoid dangerous traps", "Find the escape exit"],
    rating: 4.5,
    dateAdded: "2025-06-22"
  },
  {
    id: 68,
    slug: "idle-saga",
    title: "Idle Saga",
    description: "Begin your idle adventure saga! Build powerful teams, auto-battle for resources, unlock new heroes and skills, and write your epic legend.",
    category: "adventure",
    thumb: "images/idle-saga.avif",
    iframeUrl: "https://www.crazygames.com/embed/idle-saga",
    tags: ["adventure", "idle", "saga", "heroes", "strategy", "epic"],
    instructions: ["Build your hero team", "Set up auto-battle mode", "Collect experience and equipment", "Unlock new hero characters", "Progress through epic storylines"],
    rating: 4.7,
    dateAdded: "2025-06-22"
  },
  {
    id: 69,
    slug: "noob-digger-pro-drill-miner",
    title: "Noob Digger: Pro Drill Miner",
    description: "Grow from novice miner to professional drill master! Mine precious minerals, upgrade drilling equipment, explore the underground world's infinite treasures and secrets.",
    category: "adventure",
    thumb: "images/noob-digger-pro-drill-miner.avif",
    iframeUrl: "https://www.crazygames.com/embed/noob-digger-pro-drill-miner-cal",
    tags: ["adventure", "mining", "drilling", "upgrade", "treasure", "exploration"],
    instructions: ["Control drill machine to dig downward", "Collect minerals and gems", "Upgrade drilling equipment", "Unlock new mining areas", "Discover hidden treasures"],
    rating: 4.4,
    dateAdded: "2025-06-22"
  },
  {
    id: 70,
    slug: "animal-shopping-supermarket",
    title: "Animal Shopping Supermarket",
    description: "Run your animal supermarket! Serve cute animal customers, manage inventory, expand your store, and become the most popular animal supermarket owner.",
    category: "simulation",
    thumb: "images/animal-shopping-supermarket.avif",
    iframeUrl: "https://www.crazygames.com/embed/animal-shopping-supermarket",
    tags: ["simulation", "management", "animals", "shopping", "business", "cute"],
    instructions: ["Serve animal customers", "Manage product inventory", "Handle cashier operations to earn coins", "Upgrade and expand your supermarket", "Keep all animal customers satisfied"],
    rating: 4.5,
    dateAdded: "2025-06-22"
  },
  {
    id: 71,
    slug: "hungry-ocean-eat-feed-and-grow-fish",
    title: "Hungry Ocean: Eat, Feed and Grow Fish",
    description: "In the vast ocean, survive and grow! Start from a small fish, eat smaller ones, avoid dangerous predators, and evolve into a powerful ocean ruler.",
    category: "io",
    thumb: "images/hungry-ocean-eat-feed-and-grow-fish.avif",
    iframeUrl: "https://www.crazygames.com/embed/hungry-ocean-eat-feed-and-grow-fish",
    tags: ["io", "survival", "ocean", "fish", "evolution", "multiplayer"],
    instructions: ["Control your fish to swim", "Eat smaller fish to grow", "Avoid larger predators", "Collect food to grow faster", "Evolve into a stronger ocean creature"],
    rating: 4.6,
    dateAdded: "2025-06-22"
  },
  {
    id: 72,
    slug: "mahjongg-solitaire",
    title: "Mahjongg Solitaire",
    description: "Classic Mahjong card game! Match identical tiles, clear the board, and challenge your observation and strategy skills.",
    category: "mahjong",
    thumb: "images/mahjongg-solitaire.avif",
    iframeUrl: "https://www.crazygames.com/embed/mahjongg-solitaire",
    tags: ["mahjong", "solitaire", "puzzle", "traditional", "matching", "strategy"],
    instructions: ["Find matching Mahjong tiles", "Only select uncovered tiles", "Match two identical tiles to remove", "Clear the board to win", "Plan your moves carefully"],
    rating: 4.5,
    dateAdded: "2025-06-22"
  },
  {
    id: 73,
    slug: "piles-of-mahjong",
    title: "Piles of Mahjong",
    description: "Unique Mahjong stacking challenge! Find matching pairs in the complex Mahjong tile piles and test your spatial imagination and patience.",
    category: "mahjong",
    thumb: "images/piles-of-mahjong.avif",
    iframeUrl: "https://www.crazygames.com/embed/piles-of-mahjong",
    tags: ["mahjong", "puzzle", "3d", "stacking", "matching", "challenge"],
    instructions: ["Observe 3D Mahjong piles", "Find movable tiles", "Match identical Mahjong tiles", "Clear Mahjong piles layer by layer", "Complete all challenge levels"],
    rating: 4.4,
    dateAdded: "2025-06-22"
  },
  {
    id: 74,
    slug: "mahjong-online",
    title: "Mahjong Online",
    description: "Online Mahjong classic experience! Enjoy traditional Mahjong games with players from around the world and improve your Mahjong skills.",
    category: "mahjong",
    thumb: "images/mahjong-online.avif",
    iframeUrl: "https://www.crazygames.com/embed/mahjong-classic-webgl",
    tags: ["mahjong", "online", "multiplayer", "classic", "traditional", "skill"],
    instructions: ["Learn Mahjong basic rules", "Form Mahjong hands to score points", "Observe other players' moves", "Develop optimal strategies", "Strive for the highest score"],
    rating: 4.7,
    dateAdded: "2025-06-22"
  },
  {
    id: 75,
    slug: "hack-and-climb",
    title: "Hack and Climb",
    description: "Skill climbing challenge game! Use your tools to break through obstacles, climb dangerous heights, and test your reaction speed and operation skills.",
    category: "skill",
    thumb: "images/hack-and-climb.avif",
    iframeUrl: "https://www.crazygames.com/embed/hack-and-climb",
    tags: ["skill", "climbing", "platformer", "challenge", "precision", "timing"],
    instructions: ["Use tools to break through obstacles", "Accurately control climbing movements", "Avoid dangerous traps", "Master jump timing", "Reach the top to complete the challenge"],
    rating: 4.3,
    dateAdded: "2025-06-22"
  }
]; 
