window.GAMES = [
  {
    id: 1,
    slug: "geometry-jump",
    title: "Geometry Jump",
    description: "Jump over obstacles in this fast-paced geometry-based platformer! Time your jumps perfectly to avoid spikes and reach the finish line.",
    category: "geometry-dash",
    thumb: "images/geometry-jump.png",
    iframeUrl: "https://1games.io/game/geometry-jump/",
    tags: ["platformer", "jumping", "geometry", "arcade", "skill"],
    instructions: ["Click or spacebar to jump", "Time your jumps carefully", "Avoid spikes and obstacles", "Reach the end to complete level"],
    rating: 4.8,
    dateAdded: "2025-06-10"
  },
  {
    id: 2,
    slug: "geometry-arrow",
    title: "Geometry Arrow",
    description: "Navigate through geometric mazes with precise arrow movements! Control your arrow through challenging levels filled with obstacles.",
    category: "geometry-dash",
    thumb: "images/geometry-arrow.png",
    iframeUrl: "https://1games.io/embed/geometry-arrow",
    tags: ["geometry", "arrow", "maze", "precision", "arcade","skill"],
    instructions: ["Arrow keys to move", "Navigate through obstacles", "Collect gems along the way", "Reach the target to advance"],
    rating: 4.6,
    dateAdded: "2025-06-08"
  },
  {
    id: 3,
    slug: "wave-dash",
    title: "WAVE Dash",
    description: "Jump and fly your way through danger in this rhythm-based action platformer! Navigate through impossible levels with perfect timing.",
    category: "geometry-dash",
    thumb: "images/wave-dash.jpg",
    iframeUrl: "https://www.jopi.com/embed.php?game=geometry-dash",
    tags: ["platformer", "rhythm", "challenging", "music", "geometry","skill"],
    instructions: ["Click or spacebar to jump", "Follow the music rhythm", "Avoid spikes and obstacles", "Practice mode available"],
    rating: 4.7,
    dateAdded: "2025-06-05"
  },
  {
    id: 4,
    slug: "geometry-dash-black-wave",
    title: "Geometry Dash Black Wave",
    description: "Master the wave gamemode in this intense Geometry Dash level! Navigate through tight spaces with fluid wave movements.",
    category: "geometry-dash",
    thumb: "images/geometry-dash-black-wave.jpg",
    iframeUrl: "https://g.vseigru.net/7/igra-chjornaya-geometri-volna-super-chellendzh/",
    tags: ["wave", "geometry-dash", "challenging", "dark", "precision","skill"],
    instructions: ["Hold to go up, release to go down", "Navigate through narrow passages", "Perfect timing is essential", "Avoid hitting walls"],
    rating: 4.9,
    dateAdded: "2025-06-01"
  },
  {
    id: 5,
    slug: "geometry-dash-black-wave-2",
    title: "Geometry Dash Black Wave 2",
    description: "The sequel to Black Wave with even more challenging wave sequences! Test your skills in this advanced geometry level.",
    category: "geometry-dash",
    thumb: "images/geometry-dash-black-wave2.jpg",
    iframeUrl: "https://yandex.com/games/app/307214?utm_source=distrib&amp;utm_medium=geometrydashwave.com",
    tags: ["wave", "sequel", "hard", "geometry-dash", "expert","skill"],
    instructions: ["Hold to ascend, release to descend", "Master wave physics", "Navigate tight corridors", "Patience and practice required"],
    rating: 4.5,
    dateAdded: "2025-05-28"
  },
  {
    id: 6,
    slug: "geometry-dash-black-wave-3",
    title: "Geometry Dash Black Wave 3",
    description: "The third installment of the Black Wave series with new mechanics and obstacles! Can you conquer this ultimate wave challenge?",
    category: "geometry-dash",
    thumb: "images/geometry-dash-black-wave3.jpg",
    iframeUrl: "https://g.vseigru.net/7/igra-chjornaya-geometri-volna-super-chellendzh/",
    tags: ["wave", "trilogy", "extreme", "geometry-dash", "mechanics","skill"],
    instructions: ["Control wave movement", "Learn new wave patterns", "Adapt to changing gravity", "Complete all checkpoints"],
    rating: 4.4,
    dateAdded: "2025-05-25"
  },
  {
    id: 7,
    slug: "geometry-dash-black-wave-4",
    title: "Geometry Dash Black Wave 4",
    description: "Push your wave skills to the limit in the fourth Black Wave adventure! Experience new level design and wave challenges.",
    category: "geometry-dash",
    thumb: "images/geometry-dash-black-wave4.jpg",
    iframeUrl: "https://yandex.com/games/app/344498?utm_source=distrib&amp;utm_medium=space-waves.co&amp;clid=10575041",
    tags: ["wave", "advanced", "black-series", "geometry-dash", "skill"],
    instructions: ["Master wave control", "Navigate complex patterns", "Use checkpoints wisely", "Focus on smooth movements"],
    rating: 4.3,
    dateAdded: "2025-05-20"
  },
  {
    id: 8,
    slug: "geometry-dash-black-wave-5",
    title: "Geometry Dash Black Wave 5",
    description: "The epic finale of the Black Wave series! Face the ultimate wave challenge with the most complex patterns yet.",
    category: "geometry-dash",
    thumb: "images/geometry-dash-black-wave5.jpg",
    iframeUrl: "https://app-373298.games.s3.yandex.net/373298/r8k1p219s59kjpid5ymnkvyfb59shfd2/index.html?sdk=%2Fsdk%2F_%2Fv2.5bc8bbec2107c9209400.js#origin=https%3A%2F%2Fallwebgames.com&amp;app-id=373298&amp;device-type=desktop",
    tags: ["wave", "finale", "ultimate", "geometry-dash", "mastery","skill"],
    instructions: ["Perfect wave technique required", "Handle multiple wave types", "Memorize difficult sections", "Never give up!"],
    rating: 4.6,
    dateAdded: "2025-05-15"
  },
  {
    id: 9,
    slug: "geometry-dash-wave",
    title: "Geometry Dash Wave",
    description: "Experience pure wave gameplay in this classic Geometry Dash mode! Master the art of wave navigation through various obstacles.",
    category: "geometry-dash",
    thumb: "images/Geometry Dash Wave.jpg",
    iframeUrl: "https://www.jopi.com/embed.php?game=geometry-dash-wave",
    tags: ["wave", "classic", "geometry-dash", "pure", "original","skill"],
    instructions: ["Hold to rise, release to fall", "Control wave amplitude", "Avoid ceiling and floor", "Maintain steady rhythm"],
    rating: 4.7,
    dateAdded: "2024-11-25"
  },
  {
    id: 10,
    slug: "geometry-dash-hyper-wave-neon-challenge",
    title: "Geometry Dash Hyper Wave Neon Challenge",
    description: "Enter a neon-lit hyper wave challenge with intense visuals and fast-paced gameplay! Can you handle the speed?",
    category: "geometry-dash",
    thumb: "images/Geometry Dash Hyper Wave Neon Challenge.jpg",
    iframeUrl: "https://www.jopi.com/embed.php?game=geometry-dash-hyper-wave-neon-challenge",
    tags: ["hyper", "neon", "fast", "wave", "visual","skill"],
    instructions: ["React quickly to changes", "Handle high-speed wave", "Follow neon indicators", "Stay focused on patterns"],
    rating: 4.2,
    dateAdded: "2024-09-15"
  },
  {
    id: 11,
    slug: "smash-karts-io",
    title: "Smash Karts IO",
    description: "Race against players worldwide in this action-packed kart racing battle royale! Collect weapons and smash your opponents!",
    category: "multiplayer",
    thumb: "images/Smash Karts IO.jpg",
    iframeUrl: "https://www.jopi.com/embed.php?game=smash-karts-io",
    tags: ["racing", "multiplayer", "battle-royale", "karts", "weapons"],
    instructions: ["WASD or arrow keys to drive", "Collect weapon boxes", "Attack other players", "Be the last kart standing"],
    rating: 4.8,
    dateAdded: "2025-06-13"
  },
  {
    id: 12,
    slug: "paper-io-2",
    title: "Paper IO 2",
    description: "Conquer territory by drawing lines and creating closed shapes! Avoid other players while expanding your paper empire.",
    category: "io",
    thumb: "images/Paper IO 2.jpg",
    iframeUrl: "https://www.jopi.com/embed.php?game=paper-io-2",
    tags: ["territory", "io-game", "strategy", "multiplayer", "conquest"],
    instructions: ["Move to draw lines", "Return to your territory to claim area", "Avoid hitting other players' lines", "Expand your territory"],
    rating: 4.1,
    dateAdded: "2024-08-20"
  },
  {
    id: 13,
    slug: "geometry-dash-breeze",
    title: "Geometry Dash Breeze",
    description: "Experience a refreshing breeze of challenges in this smooth Geometry Dash level! Navigate through flowing obstacles with graceful movements.",
    category: "geometry-dash",
    thumb: "images/geometry-dash-breeze.jpg",
    iframeUrl: "https://1games.io/game/geometry-dash-breeze/",
    tags: ["geometry-dash", "breeze", "smooth", "flowing", "relaxing","skill"],
    instructions: ["Click or spacebar to jump", "Follow the gentle rhythm", "Navigate through wind-like obstacles", "Enjoy the smooth gameplay"],
    rating: 4.6,
    dateAdded: "2025-6-14"
  },
  {
    id: 14,
    slug: "geometry-dash-world",
    title: "Geometry Dash World",
    description: "Explore different worlds in this expanded Geometry Dash adventure! Travel through various themed levels with unique challenges.",
    category: "geometry-dash",
    thumb: "images/geometry-dash-world.png",
    iframeUrl: "https://1games.io/game/geometry-dash-world/",
    tags: ["geometry-dash", "world", "adventure", "themed", "exploration","skill"],
    instructions: ["Jump with spacebar or click", "Explore different world themes", "Master various level mechanics", "Unlock new worlds by progressing"],
    rating: 4.6,
    dateAdded: "2025-6-14"
  },
  {
    id: 15,
    slug: "geometry-vibes",
    title: "Geometry Vibes",
    description: "Feel the rhythm and vibes in this energetic Geometry Dash experience! Sync your movements with the beat and overcome vibrant challenges.",
    category: "geometry-dash",
    thumb: "images/geometry-vibes.webp",
    iframeUrl: "https://1games.io/embed/geometry-vibes",
    tags: ["geometry-dash", "vibes", "rhythm", "energetic", "music","skill"],
    instructions: ["Jump with spacebar or click", "Feel the music rhythm", "Navigate colorful obstacles", "Stay in sync with the beat"],
    rating: 4.7,
    dateAdded: "2025-06-15"
  },
  {
    id: 16,
    slug: "space-waves",
    title: "Space Waves",
    description: "Journey through space with wave-based gameplay! Navigate your ship through cosmic obstacles in this stellar adventure.",
    category: "geometry-dash",
    thumb: "images/space-waves.webp",
    iframeUrl: "https://crazygames.com/embed/space-waves",
    tags: ["geometry-dash", "space", "waves", "cosmic", "adventure","skill"],
    instructions: ["Hold to ascend, release to descend", "Navigate through space debris", "Collect space gems", "Avoid asteroid obstacles"],
    rating: 4.5,
    dateAdded: "2025-06-15"
  },
  {
    id: 17,
    slug: "geometry-game-3d",
    title: "Geometry Game 3D",
    description: "Experience Geometry Dash in a whole new dimension! Navigate through 3D geometric landscapes with enhanced depth and perspective.",
    category: "geometry-dash",
    thumb: "images/geometry-game-3d.webp",
    iframeUrl: "https://1games.io/embed/geometry-game-3d",
    tags: ["geometry-dash", "3d", "dimension", "perspective", "geometric","skill"],
    instructions: ["Use spacebar to jump", "Navigate 3D obstacles", "Adjust to depth perception", "Master dimensional gameplay"],
    rating: 4.6,
    dateAdded: "2025-06-15"
  },
  {
    id: 18,
    slug: "wave-road",
    title: "Wave Road",
    description: "Travel down the endless wave road with precise control! Master the art of wave navigation on this challenging geometric highway.",
    category: "geometry-dash",
    thumb: "images/wave-road.webp",
    iframeUrl: "https://1games.io/embed/wave-road",
    tags: ["geometry-dash", "wave", "road", "highway", "precision"],
    instructions: ["Control wave movement", "Stay on the road path", "Avoid falling off edges", "Maintain steady rhythm"],
    rating: 4.4,
    dateAdded: "2025-06-15"
  },
  {
    id: 19,
    slug: "food-rush",
    title: "Food Rush",
    description: "Rush through delicious food combinations in this fast-paced match-3 adventure! Match tasty treats and complete cooking challenges.",
    category: "match3",
    thumb: "images/food-rush.jpg",
    iframeUrl: "https://play.famobi.com/food-rush/A-FAMOBI-COM",
    tags: ["match3", "food", "cooking", "fast-paced", "delicious"],
    instructions: ["Match 3 or more identical food items", "Complete cooking objectives", "Use power-ups to clear obstacles", "Beat level targets within moves"],
    rating: 4.6,
    dateAdded: "2025-06-16"
  },
  {
    id: 20,
    slug: "tile-journey",
    title: "Tile Journey",
    description: "Embark on an epic tile-matching journey across mystical lands! Solve challenging puzzles and unlock ancient secrets.",
    category: "match3",
    thumb: "images/tile-journey.jpg",
    iframeUrl: "https://play.famobi.com/tile-journey/A1000-10E",
    tags: ["match3", "journey", "adventure", "mystical", "tiles"],
    instructions: ["Match 3 or more tiles of the same type", "Clear paths to progress", "Collect special artifacts", "Solve each level's unique challenge"],
    rating: 4.5,
    dateAdded: "2025-06-16"
  },
  {
    id: 21,
    slug: "diamond-rush-2",
    title: "Diamond Rush 2",
    description: "The ultimate diamond hunting adventure returns! Match sparkling diamonds and precious gems in this thrilling sequel.",
    category: "match3",
    thumb: "images/diamond-rush-2.jpg",
    iframeUrl: "https://play.famobi.com/diamond-rush-2",
    tags: ["match3", "diamond", "gems", "treasure", "sequel"],
    instructions: ["Match 3+ diamonds to collect them", "Create special gem combinations", "Complete mining objectives", "Discover rare diamond formations"],
    rating: 4.7,
    dateAdded: "2025-06-16"
  },
  {
    id: 22,
    slug: "garden-bloom",
    title: "Garden Bloom",
    description: "Create beautiful flower gardens by matching colorful blooms! Help flowers grow and bloom in this peaceful gardening puzzle.",
    category: "match3",
    thumb: "images/garden-bloom.jpg",
    iframeUrl: "https://gardenbloom.h5games.usercontent.goog/v/03uof2ceev9h8/?origin=https%3A%2F%2Framesnacks.com&amp.gameCenter1d=ramesnacks&amp",
    tags: ["match3", "garden", "flowers", "nature", "peaceful"],
    instructions: ["Match flower buds to make them bloom", "Create garden patterns", "Use garden tools for special effects", "Complete seasonal challenges"],
    rating: 4.4,
    dateAdded: "2025-06-16"
  },
  {
    id: 23,
    slug: "garden-match-3d",
    title: "Garden Match 3D",
    description: "Experience match-3 in stunning 3D! Design and maintain beautiful gardens while solving engaging three-dimensional puzzles.",
    category: "match3",
    thumb: "images/garden-match-3d.jpg",
    iframeUrl: "https://play.famobi.com/garden-match-3d",
    tags: ["match3", "3d", "garden", "design", "beautiful"],
    instructions: ["Match items in 3D space", "Rotate view to find matches", "Decorate your garden", "Complete landscaping projects"],
    rating: 4.6,
    dateAdded: "2025-06-16"
  },
  {
    id: 24,
    slug: "zoo-boom",
    title: "Zoo Boom",
    description: "Join the wildest zoo adventure! Match animal tiles and help zoo animals in this explosive and fun-filled puzzle game.",
    category: "match3",
    thumb: "images/zoo-boom.jpg",
    iframeUrl: "https://play.famobi.com/zoo-boom",
    tags: ["match3", "zoo", "animals", "explosive", "adventure"],
    instructions: ["Match 3 or more animal tiles", "Rescue zoo animals", "Create powerful animal combos", "Complete zoo missions"],
    rating: 4.5,
    dateAdded: "2025-06-16"
  },
  {
    id: 25,
    slug: "bubble-woods",
    title: "Bubble Woods",
    description: "Pop your way through enchanted forest bubbles! Aim, match colors, and clear the magical woodland in this bubble shooter adventure.",
    category: "match3",
    thumb: "images/bubble-woods.jpg",
    iframeUrl: "https://play.famobi.com/bubble-woods",
    tags: ["match3", "bubble", "forest", "magical", "shooter"],
    instructions: ["Aim and shoot colored bubbles", "Match 3+ bubbles of same color", "Clear forest paths", "Use special bubble power-ups"],
    rating: 4.7,
    dateAdded: "2025-06-16"
  },
  {
    id: 26,
    slug: "totemia-cursed-marbles",
    title: "Totemia: Cursed Marbles",
    description: "Break the ancient curse by matching mystical marbles! Shoot colored marbles to create matches and solve totemic puzzles.",
    category: "match3",
    thumb: "images/totemia-cursed-marbles.jpg",
    iframeUrl: "https://play.famobi.com/totemia-cursed-marbles",
    tags: ["match3", "marbles", "ancient", "mystical", "curse"],
    instructions: ["Shoot marbles to create matches", "Match 3+ marbles of same color", "Break the marble chains", "Complete totemic challenges"],
    rating: 4.8,
    dateAdded: "2025-06-16"
  }
]; 
